"reference name '%s' is reserved" = "引用名 '%s' 被保留"
"reference '%s' not exist" = "引用 '%s' 不存在"
"branch '%s' not exist" = "分支 '%s' 不存在"
"refusing to delete the current branch: " = "拒绝删除当前分支："
"reference is already locked: %s" = "引用已被锁定：%s"
"update reference error: %v" = "更新引用错误：%v"
"objects verified" = "objects 已验证"
"check integrity error: %v" = "检查完整性错误：%v"
"tag is updated, please update and try again" = "tag 已更新，请更新后重试"
"branch is updated, please update and try again" = "分支已更新，请更新后重试"
"internal server error" = "内部服务器错误"
"internal server error: %v" = "内部服务器错误：%v"
"'%s' is not a valid branch name" = "'%s' 不是有效的分支名"
"'%s' is not a valid object name" = "'%s' 不是有效的对象名"
"'%s' is not a valid reference name" = "'%s' 不是有效的对象引用名"
"'%s' is protected branch, cannot be modified" = "'%s' 是保护分支, 无法被修改，请推送到其他分支或修改保护分支设置"
"'%s' is archived, cannot be modified" = "'%s' 已归档, 无法被修改"
